package com.uop.recordingtools.service;

import com.uop.recordingtools.storage.DataStore; import com.uop.recordingtools.util.Items;
import org.bukkit.Material; import org.bukkit.entity.Player; import org.bukkit.inventory.ItemStack; import org.bukkit.plugin.java.JavaPlugin; import java.util.*;
public final class ArmorService {
 private final DataStore store; public ArmorService(JavaPlugin p,DataStore s){store=s;}
 public boolean set(Player p,String matName,String mode,boolean weapons,List<String> weaponNames){Material chest=Items.material(matName);if(chest==null)return false;int lvl=Items.level(mode,mode);ItemStack[] armor={Items.armor(chest,"head"),Items.armor(chest,"chest"),Items.armor(chest,"legs"),Items.armor(chest,"feet")};if(!mode.equalsIgnoreCase("plain")){for(ItemStack i:armor)enchantArmor(i,lvl);}p.getInventory().setArmorContents(armor);if(weapons)giveWeapons(p,weaponNames,mode,lvl);return true;}
 private void enchantArmor(ItemStack i,int lvl){var prot=Items.enchantment("protection");if(prot!=null)Items.enchant(i,prot,lvl);}
 public void giveWeapons(Player p,List<String> names,String mode,int lvl){if(names==null||names.isEmpty())return;for(String n:names){Material m=switch(n.toLowerCase(Locale.ROOT)){case "sword"->Material.NETHERITE_SWORD;case "mace"->Material.MACE;case "axe"->Material.NETHERITE_AXE;case "bow"->Material.BOW;case "crossbow"->Material.CROSSBOW;case "trident"->Material.TRIDENT;case "pickaxe"->Material.NETHERITE_PICKAXE;case "shovel"->Material.NETHERITE_SHOVEL;case "hoe"->Material.NETHERITE_HOE;default->null;};if(m==null)continue;ItemStack i=new ItemStack(m);if(!mode.equalsIgnoreCase("plain")){if(m.name().contains("SWORD")||m.name().contains("AXE"))Items.enchant(i,Items.enchantment("sharpness"),lvl);if(m==Material.BOW)Items.enchant(i,Items.enchantment("power"),lvl);if(m==Material.CROSSBOW)Items.enchant(i,Items.enchantment("quick_charge"),lvl);if(m==Material.TRIDENT)Items.enchant(i,Items.enchantment("impaling"),lvl);}p.getInventory().addItem(i);}}
 public void saveLoadout(String name,Player p){String base="loadouts."+name;store.set(base+".owner",p.getUniqueId().toString());store.set(base+".ownerName",p.getName());store.set(base+".inventory",Arrays.asList(p.getInventory().getContents()));store.set(base+".armor",Arrays.asList(p.getInventory().getArmorContents()));store.set(base+".offhand",Arrays.asList(p.getInventory().getItemInOffHand()));store.saveNow();}
 public boolean giveSaved(String name,Player p){if(!store.data().contains("loadouts."+name))return false;List<?> inv=store.data().getList("loadouts."+name+".inventory"),armor=store.data().getList("loadouts."+name+".armor"),off=store.data().getList("loadouts."+name+".offhand");p.getInventory().setContents(deserialize(inv,41));p.getInventory().setArmorContents(deserialize(armor,4));ItemStack[] o=deserialize(off,1);p.getInventory().setItemInOffHand(o[0]);return true;}
 public Set<String> loadouts(){var sec=store.data().getConfigurationSection("loadouts");return sec==null?Set.of():sec.getKeys(false);}public void delete(String name){store.remove("loadouts."+name);store.saveNow();}
 private ItemStack[] deserialize(List<?> l,int size){ItemStack[] a=new ItemStack[size];Arrays.fill(a,new ItemStack(Material.AIR));if(l!=null)for(int i=0;i<Math.min(size,l.size());i++)if(l.get(i) instanceof ItemStack x)a[i]=x;return a;}
}
